
settings:
  # Default cooldown for guardian stones(in minutes)
  cooldown: 5
  # Maximum amount of time to be affected by a potion effect(in seconds)
  # This does not affect rewards bought in the Hunted store
  # This also does not affect actual potion items found
  max-effect-length: 60
  # Minimum effect length of potions(in seconds)
  # This does not effect rewards bought in the Hunted store
  # This also does not affect actual potion items
  min-effect-length: 10
  # Maximum enchant level possible
  max-enchant-level: 2
  # Can players receive potions when they spawn into Hunted
  can-receive-potions: false
  # Max potions a player can receive as a reward
  max-potions: 2
  # The chance a potion will be tier 2 (n%)
  potion-tier2-chance: 1
  # Maximum potion amplifier level(starts at 0)
  max-amplifier-level: 1
  # The chance that when a player gets a smite reward, they also get teleported to a random location (n/100)
  smite-teleport-chance: 5
  # Radius in which to search for nearby players(for certain rewards)
  radius: 50
  # Chance the player will receive an ascented item(n%)
  ascented-item-chance: 10
  # Chance a player can receive two effects from a guardian stone(n%)
  receive-effect-twice: 10
  # Max arrows a player can receive as a reward, max 64
  max-arrows: 32
  # World to use for Hunted
  world: world
  # What map configuration is currently active
  # If empty, will use the first one found.
  active-map-configuration: ''
  # If signs can be used to enter the Hunted world
  sign-entrance: true
  # If signs can be used to leave the Hunted world
  sign-exit: true
  # If signs can be used to enter the Hunted world
  portal-entrance: true
  # If signs can be used to leave the Hunted world
  portal-exit: true
  # How far this plugin should check for signs to enter/exit the Hunted world.
  sign-depth: 1
  # How far this plugin should check for signs underneath portals on entrance/exit on Hunted.
  portal-sign-depth: 2
