
settings:
  # Default cooldown for guardian stones(in minutes)
  cooldown: 5
  # Maximum amount of time to be affected by a potion effect(in seconds)
  # This does not affect rewards bought in the Hunted store
  # This also does not affect actual potion items found
  max-effect-length: 60
  # Minimum effect length of potions(in seconds)
  # This does not effect rewards bought in the Hunted store
  # This also does not affect actual potion items
  min-effect-length: 10
  # Maximum enchant level possible
  max-enchant-level: 2
  # Can players receive potions when they spawn into Hunted
  can-receive-potions: false
  # Max potions a player can receive as a reward
  max-potions: 2
  # The chance a potion will be tier 2 (n%)
  potion-tier2-chance: 10
  # Maximum potion amplifier level(starts at 0)
  max-amplifier-level: 1
  # The chance that when a player gets a smite reward, they also get teleported to a random location (n/100)
  smite-teleport-chance: 10
  # Radius in which to search for nearby players
  radius: 50
  # Chance the player will receive an ascented item(n/100)
  ascented-item-chance: 10
  # Chance a player can receive two effects from a guardian stone
  receive-effect-twice: 10
  # Max arrows a player can receive as a reward, max 64
  max-arrows: 32
  # World to use for Hunted
  world: world
  # Debug - don't touch this unless you like spam
  # Also, you need a certain permission to see debug messages, just in case
  debug: false

# MYSQL Database information
# Please triple-check this information!
database:
  host: 'localhost'
  port: 3306
  name: 'Hunted'
  username: 'root'
  password: ''