name: Hunted
version: 0.1
description: Hunted plugin for BTC's server
author: Senmori
main: net.senmori.hunted.Hunted
commands:
  hunted:
    description: Main hunted plugin command
    aliases: [ht]
permissions:
  hunted.commands.add:
  	default: false
  hunted.commands.delete:
  	default: false
  hunted.commands.edit:
  	default: false
  hunted.commands.list:
    default: false
  hunted.debug.receive:
  	default: false
  hunted.admin.break:
    default: false
  hunted.admin.place:
    default: false
  hunted.admin.*:
    children:
      hunted.admin.break: true
      hunted.admin.place: true
  hunted.commands.*:
    children:
      hunted.commands.add: true
      hunted.commands.delete: true
      hunted.commands.edit: true
      hunted.commands.list: true
  	  