name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}
main: ${main.Class}
commands:
    ht:
        description: Hunted plugin command
        aliases: [hunted]
permissions:
    hunted.interact.user:
        default: true
        children:
            hunted.interact.stone.guardian: true
            hunted.interact.stone.teleport: true
            hunted.commands.stuck: true
    hunted.commands.admin:
        default: false
        children:
            hunted.interact.user: true
            hunted.commands.add: true
            hunted.commands.delete: true
            hunted.commands.edit: true
            hunted.commands.list: true
            hunted.commands.exempt: true
            hunted.commands.stuck.other: true
    hunted.interact.admin:
        default: false
        children:
            hunted.admin.break: true
            hunted.admin.place: true
    hunted.admin.exempt:
        default: false
